# http://docs.travis-ci.com/user/languages/objective-c/
# https://github.com/facebook/xctool

language: objective-c

osx_image: xcode7

script:

  xctool
  -project Pulser.xcodeproj
  -scheme Pulser
  -sdk iphonesimulator9.0
  -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
  build 
  test
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO

before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool
